create table lesson_topic(
    id bigint generated by default as identity primary key,
    lesson_id bigint not null references lesson(id) on delete cascade,
    topic_id bigint not null references topic(id) on delete cascade,
    mastery_level int check (mastery_level between 1 and 5),
    teacher_note text,
    unique(lesson_id, topic_id)
);