server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tutortrack?currentSchema=auth_schema
    username: postgres #tutortrack_user
    password: admin #tutortrack_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: auth_schema
    locations:
      - classpath:db/migration/postgresql
      - classpath:db/seed/postgresql

jwt:
  secret: YB5DinYKCMeVXoUUjmWVnSKNBGfeeNkH
  expiration: 86400000

logging:
  level:
    com.tutortrack: DEBUG
    org.springframework.security: DEBUG